name = "actionflare"
main = "src/index.ts"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
logpush = true
routes = ["actionflare.dev/*"]

[placement]
mode = "smart"

[vars]
NAME = "actionflare"
ENVIRONMENT = "production"
AXIOM_DATASET = "workers"
AXIOM_DATASET_OTEL = "workers-otel"

