name: Branches

on:
  push:
    branches-ignore: ['main']

env:
  FORCE_COLOR: 1

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --child-concurrency=10
      - name: Check & Test
        run: bun runx ci check
