name: Release

on:
  push:
    branches: ['main']

env:
  EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
  EARTHLY_ORG: jahands
  EARTHLY_SATELLITE: mini-sat
  FORCE_COLOR: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: earthly/actions-setup@v1.0.13
        with:
          version: v0.8.15
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - name: Deploy
        run: earthly --ci --push +deploy --GITHUB_ACTIONS=1

  create-release-pr:
    # Release PRs are for changelogs only - we auto publish on main every time regardless.
    name: Create Release PR
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency: ${{ github.workflow }}-create-release-pr
    needs: test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --child-concurrency=10
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
