name: Test

on:
  push:

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: Test
    runs-on:
      - self-hosted
      - X64
    timeout-minutes: 5
    steps:
      - uses: earthly/actions-setup@v1.0.13
        with:
          version: v0.8.15
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - uses: 1password/install-cli-action@v1
      - uses: extractions/setup-just@v3
        with:
          just-version: 1.40.0
      - name: Install Dagger
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: '0.18.6'
      - name: Test (Dagger)
        run: just dagger-test --GITHUB_ACTIONS=1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
